export const information = {
  dates: {
    maximum: "2024-01-10",
    minimum: "2023-11-29",
  },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/jXJxMcVoEuXzym3vFnjqDW4ifo6.jpg",
      genre_ids: [28, 12, 14],
      id: 572802,
      original_language: "en",
      original_title: "Aquaman and the Lost Kingdom",
      overview:
        "아틀란티스 왕국을 이끌 왕의 자리에 오른 아쿠아맨. 그 앞에 블랙 만타가 세상을 뒤흔들 강력한 지배 아이템 블랙 트라이던트를 손에 넣게 된다. 그동안 겪지 못 했던 최악의 위협 속 아쿠아맨은 블랙 만타와 손을 잡았던 이복 동생 옴 없이는 절대적 힘이 부족한 상황. 바다를 지배할 슈퍼 히어로가 세상의 판도를 바꾼다!",
      popularity: 1722.55,
      poster_path: "/eDps1ZhI8IOlbEC7nFg6eTk4jnb.jpg",
      release_date: "2023-12-20",
      title: "아쿠아맨과 로스트 킹덤",
      video: false,
      vote_average: 6.493,
      vote_count: 351,
    },
    {
      adult: false,
      backdrop_path: "/k1KrbaCMACQiq7EA0Yhw3bdzMv7.jpg",
      genre_ids: [16, 10751, 10402, 14, 35],
      id: 901362,
      original_language: "en",
      original_title: "Trolls Band Together",
      overview:
        "전 세계 모든 트롤을 열광케 했던 최고의 아이돌 그룹 ‘브로존’. 역대급 무대 실수와 형제 간의 불화로 결국 해체한 뒤, 모두에게 잊혀 간다. 그러던 어느 날, ‘브로존’의 황금막내 ‘브랜치’는 메인보컬 ‘플로이드’가 슈퍼스타 ‘벨벳’과 ‘비니어’에게 잡혀 재능을 빼앗기고 있다는 소식을 듣는다. 그를 구하기 위해서는 흩어져 있는 ‘브로존’을 재결합하고 완벽한 화음을 되찾아야 하는데… 12월, 가장 짜릿한 컴백 무대의 시작!",
      popularity: 705.291,
      poster_path: "/7M2pc9OboapgtoBbkU49Aim7O5B.jpg",
      release_date: "2023-12-20",
      title: "트롤 밴드 투게더",
      video: false,
      vote_average: 7.148,
      vote_count: 460,
    },
    {
      adult: false,
      backdrop_path: "/ptz5ETMxDoRRiE69BVuIxJzyTEO.jpg",
      genre_ids: [16, 28, 12, 35, 10751],
      id: 940551,
      original_language: "en",
      original_title: "Migration",
      overview:
        "가족을 과잉보호하는 아빠 ‘맥’ 때문에 평생을 작은 연못에서 안전하게 살아온 말러드 가족. 하지만 호기심 가득한 남매 ‘댁스’와 ‘그웬’을 위해 새로운 세상을 모험하고 싶은 엄마 ‘팸’의 설득으로 가족들은 항상 꿈꿔온 자메이카로 생애 첫 가족 모험을 떠나기로 한다! 설렘 넘치는 시작과 달리 태풍을 만나 길을 잃고, 낯선 친구들을 만나고, 위험 가득한 뉴욕에 불시착하게 된다. 인생 처음으로 모든 계획이 틀어지고 위기에 빠진 말러드 가족은 서툴지만 서로를 의지하며 모험을 계속한다. 새로운 세상, 함께라면 두려울 것 없어!",
      popularity: 519.179,
      poster_path: "/2xE3NI6zElWhwN9WJ92fqbZKmzZ.jpg",
      release_date: "2024-01-10",
      title: "인투 더 월드",
      video: false,
      vote_average: 7.1,
      vote_count: 73,
    },
    {
      adult: false,
      backdrop_path: "/ehumsuIBbgAe1hg343oszCLrAfI.jpg",
      genre_ids: [16, 10751, 14, 12],
      id: 1022796,
      original_language: "en",
      original_title: "Wish",
      overview:
        "마음 속 깊이 ‘소원’을 품고 있는 모두를 위한 디즈니의 마법! 용감한 ‘아샤’와 신비로운 ‘별’의 특별한 여정 & 소원과 얽힌 비밀스러운 힘을 지닌 ‘매그니피코 왕’의 숨겨진 스토리까지! 2024년 1월, 믿고 듣는 디즈니표 명품 OST와 함께 아름다운 로사스 왕국에서 펼쳐지는 가슴 벅찬 이야기!",
      popularity: 419.834,
      poster_path: "/lnOgP8Fl2dQ73d4Qu24O2zcKFFS.jpg",
      release_date: "2024-01-03",
      title: "위시",
      video: false,
      vote_average: 6.5,
      vote_count: 219,
    },
    {
      adult: false,
      backdrop_path: "/iiXliCeykkzmJ0Eg9RYJ7F2CWSz.jpg",
      genre_ids: [28, 53, 80],
      id: 762430,
      original_language: "en",
      original_title: "Retribution",
      overview:
        "대규모 자금을 운용하는 펀드 매니저 ‘매트’(리암 니슨)에게 걸려온 한 통의 미확인 발신자 전화!  그의 요구는 2억 8천만 유로를 송금할 것, 전화를 끊거나 차를 멈추지 말 것!",
      popularity: 369.906,
      poster_path: "/jJNgvme2a51MRCJoE7dL4Vpzv8Z.jpg",
      release_date: "2023-12-06",
      title: "레트리뷰션",
      video: false,
      vote_average: 6.902,
      vote_count: 789,
    },
    {
      adult: false,
      backdrop_path: "/dZbLqRjjiiNCpTYzhzL2NMvz4J0.jpg",
      genre_ids: [27, 53],
      id: 951491,
      original_language: "en",
      original_title: "Saw X",
      overview:
        "존은 암을 치료할 수 있는 기적을 기대하며 위험하고 실험적인 의료 시술을 받기 위해 멕시코로 떠났지만, 이 모든 수술이 가장 취약한 사람들을 속이기 위한 사기라는 사실을 알게 된다",
      popularity: 333.337,
      poster_path: "/bvwEkotIuHxjuSCEXhhSna0BqQT.jpg",
      release_date: "2023-12-13",
      title: "쏘우 X",
      video: false,
      vote_average: 7.384,
      vote_count: 1351,
    },
    {
      adult: false,
      backdrop_path: "/f1AQhx6ZfGhPZFTVKgxG91PhEYc.jpg",
      genre_ids: [18, 36, 10752],
      id: 753342,
      original_language: "en",
      original_title: "Napoleon",
      overview:
        "프랑스군 지휘관이었던 나폴레옹의 기원과 빠르고 냉혹하게 황제 자리에 오르게 된 이야기를 아내이자 유일한 참사랑이었던 조세핀과 맺었던 중독적이고 불안정한 관계를 통해 가까이서 들여다본다.",
      popularity: 251.864,
      poster_path: "/cFOpMbj28ZKhXDy50mrIcLhLb8g.jpg",
      release_date: "2023-12-06",
      title: "나폴레옹",
      video: false,
      vote_average: 6.371,
      vote_count: 857,
    },
    {
      adult: false,
      backdrop_path: "/1HHp75V06ymY19lRqU7EPRv55Jt.jpg",
      genre_ids: [12, 16, 14],
      id: 872976,
      original_language: "ja",
      original_title: "デジモンアドベンチャー02 THE BEGINNING",
      overview:
        "모험의 날로부터 10년이 지난 2012년. 선택받은 아이들과 파트너 디지몬은 변함없는 우정을 지켜왔다. 그러던 어느 날, 도쿄 상공에 나타난 디지몬 알이 전 세계로 메시지를 보낸다. 전 세계가 주목하는 가운데, ‘산해’와 친구들 앞에 자신이 최초의 선택받은 아이라고 주장하는 ‘루이’가 나타나는데… 선택받은 아이의 탄생의 비밀에는 어린 시절 ‘루이’의 단 하나의 소원이 숨겨져 있었다. 과거와 현재, 그리고 모든 것이 연결될 때, 디지몬 사상 최대의 위기가 찾아온다! 지금, 어른이 된 선택받은 아이들의 새로운 모험의 문이 열린다!",
      popularity: 129.134,
      poster_path: "/3KkwgcCMfpADx1Ya4Hcwt1OHRv3.jpg",
      release_date: "2023-11-29",
      title: "극장판 파워 디지몬 더 비기닝",
      video: false,
      vote_average: 6.8,
      vote_count: 5,
    },
    {
      adult: false,
      backdrop_path: "/et0G74BxoBgNQEZBkUcVhsgeRFF.jpg",
      genre_ids: [18, 10749, 10402],
      id: 523607,
      original_language: "en",
      original_title: "Maestro",
      overview:
        "음악의 전설 레너드 번스타인과 펠리시아 몬테알레그레 콘 번스타인. 평생에 걸친 두 사람의 복잡한 관계를 따라가는 거침없는 사랑 이야기.",
      popularity: 133.444,
      poster_path: "/moiFIJn0vplfmucUDntyj4c11T.jpg",
      release_date: "2023-12-06",
      title: "마에스트로 번스타인",
      video: false,
      vote_average: 6.553,
      vote_count: 235,
    },
    {
      adult: false,
      backdrop_path: "/bW2R6PejAFk6FVCyLmTsgn8ETqZ.jpg",
      genre_ids: [28, 878],
      id: 634429,
      original_language: "ja",
      original_title: "シン・ウルトラマン",
      overview:
        "일본 전역에서 정체불명의 괴수가 잇따라 출현하자 정부는 이들을 ‘화위수’라 명명하고 대응팀 ‘화특대’를 신설한다. ‘화위수’에 의한 국가적 위기가 임박해진 와중, 돌연 은빛의 거인이 나타나 ‘화위수’를 퇴치한다. 거인의 정체를 알아내기 위해 투입된 분석관 ‘아사미’는 그것에 ‘울트라맨’이라는 이름을 붙인다. 며칠 후, 이번에는 외성인에 의해 다시 위기에 빠진 ‘화특대’. 그 때, 어디선가 ‘울트라맨’이 나타나 ‘화특대’ 기지를 파괴하고 그를 아군이라 생각했던 인간들은 혼란에 빠지는데…",
      popularity: 60.209,
      poster_path: "/kyIFa7jROnKEGY6R6XXWTNOzu5E.jpg",
      release_date: "2023-12-06",
      title: "신 울트라맨",
      video: false,
      vote_average: 7.141,
      vote_count: 110,
    },
    {
      adult: false,
      backdrop_path: "/vAsxVpXP53cMSsD9u4EekQKz4ur.jpg",
      genre_ids: [18, 53],
      id: 1050035,
      original_language: "ja",
      original_title: "怪物",
      overview:
        "싱글맘 사오리는 아들 미나토의 행동에서 이상 기운을 감지한다. 용기를 내 찾아간 학교에서 상담을 진행한 날 이후 선생님과 학생들의 분위기가 심상치 않게 흐르기 시작하고.  한편 사오리는 친구들로부터 따돌림을 당하고 있는 미나토의 친구 요리의 존재를 알게 되고 자신이 아는 아들의 모습과 사람들이 아는 아들의 모습이 다르다는 사실을 어렴풋이 깨닫는데… 태풍이 몰아치던 어느 날, 아무도 몰랐던 진실이 드러난다.",
      popularity: 66.322,
      poster_path: "/cHS3uVwAyViWcVbpRwrfekgn2cr.jpg",
      release_date: "2023-11-29",
      title: "괴물",
      video: false,
      vote_average: 8.183,
      vote_count: 52,
    },
    {
      adult: false,
      backdrop_path: "/cru4rjGcdHGhnPyjNXvW82jOrif.jpg",
      genre_ids: [35, 18, 10749],
      id: 986280,
      original_language: "fi",
      original_title: "Kuolleet lehdet",
      overview:
        "2024년, 헬싱키의 외로운 두 영혼 안사와 홀라파는 어느 날 우연히 만나 눈길을 주고받는다. “그럼 또 만날까요? 근데 이름도 모르네요” “다음에 알려줄게요” 서로의 이름도, 주소도 알지 못한 채 유일하게 받아 적은 전화번호마저 잃어버린다. 운명이 이들을 갈라놓으려 할 때 두 사람은 다시 만날 수 있을까?",
      popularity: 66.772,
      poster_path: "/3D3w06xQtFcFEFuYuv9D6m93fJM.jpg",
      release_date: "2023-12-20",
      title: "사랑은 낙엽을 타고",
      video: false,
      vote_average: 7.08,
      vote_count: 131,
    },
    {
      adult: false,
      backdrop_path: "/oeBom7DLr85lixEkWOGmhCPEfuY.jpg",
      genre_ids: [80, 18, 53],
      id: 842942,
      original_language: "en",
      original_title: "Bandit",
      overview:
        "1985년, 미시간 교도소에서 탈옥해 캐나다로 건너간 한 남자. 노숙자에게 22달러에 신분증을 구매해 ‘로버트 화이트만’으로 새로운 삶을 시작하고, 돈을 마련하기 위해 은행 강도에 나선다. 변장과 은행털이에 남다른 재능을 발견한 그는 비행기를 타고 캐나다 전역을 누비며 무려 59번의 강도 행각을 벌이는데…",
      popularity: 49.373,
      poster_path: "/a8v0tN3D0sFwBH2YVuQRpzhUE0i.jpg",
      release_date: "2023-12-28",
      title: "밴디트",
      video: false,
      vote_average: 6.2,
      vote_count: 249,
    },
    {
      adult: false,
      backdrop_path: "/5ut2rC5H1YE0GnNPpl1csnNvqum.jpg",
      genre_ids: [28, 18, 80],
      id: 1093485,
      original_language: "cn",
      original_title: "掃毒3︰人在天涯",
      overview:
        "오랜 친구 사이인 경찰 즈위안(고천락)과 장젠싱(곽부성)은 홍콩을 주름잡는 마약 조직의 보스 캉쑤차를 검거하기 위해 언더커버로 잠입한다. 그를 체포하기 위해 즈위안은 캉쑤차에게 자신의 정체를 밝히고 대립하지만, 그 과정에서 장젠싱이 총에 맞게 된다. 즈위안은 장젠싱을 구하려고 하지만 캉쑤차가 먼저 그를 데리고 골든 트라이앵글로 도망친다. 그곳에서 다친 몸을 회복하던 장젠싱은 자신을 진심으로 대해 주는 캉쑤차를 보며 자신의 역할에 대해 혼란에 빠진다. 그러던 중 캉쑤차를 잡기 위해 홍콩 경찰은 인터폴과 합심하여 소탕 작전을 계획하고 골든 트라이앵글에서 마약 밀매를 시도하던 캉쑤차의 숨통을 서서히 조여오는데…",
      popularity: 48.957,
      poster_path: "/pqxbu7Ue8717AncQKXMPTP8zAmO.jpg",
      release_date: "2023-12-07",
      title: "화이트 스톰 3",
      video: false,
      vote_average: 6.326,
      vote_count: 43,
    },
    {
      adult: false,
      backdrop_path: "/ksZTspehDCC4PCZN8ci31pFT6yp.jpg",
      genre_ids: [36, 28, 18, 10752],
      id: 660360,
      original_language: "ko",
      original_title: "노량: 죽음의 바다",
      overview:
        "임진왜란 발발로부터 7년이 지난 1598년 12월. 이순신은 왜군의 수장이던 도요토미 히데요시가 갑작스럽게 사망한 뒤 왜군들이 조선에서 황급히 퇴각하려 한다는 것을 알게 된다. 왜군을 완벽하게 섬멸하는 것이 이 전쟁을 올바르게 끝나는 것이라 생각한 이순신은 명나라와 조명연합함대를 꾸려 왜군의 퇴각로를 막고 적들을 섬멸하기로 결심한다. 하지만 왜군의 뇌물 공세에 넘어간 명나라 도독 진린은 왜군에게 퇴로를 열어주려 하고, 설상가상으로 왜군 수장인 시마즈의 살마군까지 왜군의 퇴각을 돕기 위해 노량으로 향하는데…",
      popularity: 29.887,
      poster_path: "/8WQUoHLalZfFIXlCJnfdJZyoAu6.jpg",
      release_date: "2023-12-20",
      title: "노량: 죽음의 바다",
      video: false,
      vote_average: 7,
      vote_count: 5,
    },
    {
      adult: false,
      backdrop_path: "/6A42xrhuyHboDRCsEOkMI0RZicS.jpg",
      genre_ids: [18],
      id: 760099,
      original_language: "en",
      original_title: "Living",
      overview:
        "매일 정해진 시간에 기차를 타고 집과 직장을 오가며 기계처럼 반복적인 일상을 살던 런던시청 공무원 윌리엄스 씨는 자신에게 살날이 불과 몇 달밖에 안 남았다는 소식을 듣게 된다. 난생 처음으로 인생을 즐겨 보기로 결심한 그는 바닷가 휴양지에서 술과 노래에 취해 보기도 하고 직장 동료였던 마거릿과 값비싼 레스토랑에 가보기도 하며 남은 시간을 만끽하고자 한다. 그러던 그는 문득 사무실 책상에 먼지 쌓인 채 놓여 있던 서류 하나를 생각해 내고, 남아있는 나날을 보낼 생애 가장 찬란한 선택을 하게 되는데…",
      popularity: 44.12,
      poster_path: "/t2SO7aNLXqMaRUU7znblBBsX7SW.jpg",
      release_date: "2023-12-13",
      title: "리빙: 어떤 인생",
      video: false,
      vote_average: 7.042,
      vote_count: 309,
    },
    {
      adult: false,
      backdrop_path: "/aspjY3LjTkF7NnXkIYM8fBh9g9m.jpg",
      genre_ids: [18, 10749],
      id: 962571,
      original_language: "ur",
      original_title: "جوائے لینڈ",
      overview:
        "메이크업 아티스트로 자신의 일에 열정적인 뭄타즈는 섬세한 남편 하이더르, 가족 내에서 절대자로 군림하는 시아버지 아만, 큰형 내외 및 그들의 네 딸과 함께 산다. 몇 년째 전업주부로 살던 하이더르는 카리스마 있는 트랜스젠더 뮤지션 비바의 백댄서로 취직하게 되고, 그와 동시에 뭄타즈는 전업주부가 될 것을 강요받는다. 하이더르는 첫 만남부터 강렬했던 비바에게 이끌리고, 뭄타즈는 원치 않는 임신으로 답답함을 느낀다.",
      popularity: 41.777,
      poster_path: "/db4jOt0qxdriDtUsAvqDICBj93p.jpg",
      release_date: "2023-12-03",
      title: "조이랜드",
      video: false,
      vote_average: 7.775,
      vote_count: 91,
    },
    {
      adult: false,
      backdrop_path: "/fTLMsF3IVLMcpNqIqJRweGvVwtX.jpg",
      genre_ids: [28, 80, 53],
      id: 1035806,
      original_language: "en",
      original_title: "Detective Knight: Independence",
      overview:
        "경찰의 꿈이 좌절된 후 구급대원으로 일하는 ‘데지’는 사망한 경찰의 유니폼과 뱃지를 훔쳐 경찰 행세를 하고 다닌다. 형사 ‘나이트’는 절도 사건의 범인을 찾기 위해 나서고 미국 전역이 떠들썩한 7월 4일 독립기념일, 한 은행에서 끔찍한 테러가 발생하는데…  정의를 되찾기 위한 형사 ‘나이트’의 마지막 작전이 시작된다!",
      popularity: 32.691,
      poster_path: "/lToatxNfAKj41PBgQtKGuOmChz9.jpg",
      release_date: "2023-12-13",
      title: "인디펜던스 나이트",
      video: false,
      vote_average: 5.406,
      vote_count: 154,
    },
    {
      adult: false,
      backdrop_path: "/iM1wOfDKbGaUcNzOJJWGhdifP6.jpg",
      genre_ids: [10402, 99],
      id: 1185743,
      original_language: "en",
      original_title: "Renaissance: A Film by Beyoncé",
      overview:
        '영화 "ENAISSANCE: A FILM BY BEYONCE"는 RENAISSANCE 월드 투어의 첫 공연이었던 스웨덴 스톡홀름부터 피날레 공연인 미국 미주리 주 캔자스시티까지의 여정을 모두 담고 있다. 비욘세(Beyonce)는 이번 투어가 만들어지는 모든 제작 과정에 연출을 주도하며, 그녀가 쌓아온 레거시를 대변하는 크리에이티브와 그녀가 이 투어를 하게 된 이유 등이 이 공연 실황에 모두 녹아 있다. 찬사가 끊이지 않는 비욘세(Beyonce)의 이번 "RENAISSANCE" 월드 투어는 270만명 이상의 팬들에게 단순한 공연이 아닌 \'자유의 안식처\'이 되어, 팬들과 함께 현장에서 환희와 열기를 나눴다.',
      popularity: 32.228,
      poster_path: "/1nvX59GWRgwWwBbc0kM1aCeBhgl.jpg",
      release_date: "2023-12-21",
      title: "르네상스 필름 바이 비욘세",
      video: false,
      vote_average: 8.719,
      vote_count: 16,
    },
    {
      adult: false,
      backdrop_path: "/2T2SK3bLqfd3CuUG5Z8nbtYnfwO.jpg",
      genre_ids: [10749],
      id: 1124348,
      original_language: "ja",
      original_title: "交換ウソ日記",
      overview:
        "‘노조미’는 자신의 책상 서랍 속 ‘좋아해’라는 쪽지를 발견한다. 쪽지의 주인공은 바로 학교 최고 인기남 ‘세토야마’! 전교생이 좋아하는 이상형으로부터 고백받은 설렘도 잠시, 고백의 주인이 사실은 자신이 아니었음을 알고 망연자실한다. 엇갈릴수록 점점 커져가는 너를 향한 마음, 내일은 너에게 말할 수 있을까?",
      popularity: 33.66,
      poster_path: "/qQnUTYG67LqX2RwUuzrZarhBDi3.jpg",
      release_date: "2023-12-13",
      title: "말하고 싶은 비밀",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
  ],
  total_pages: 4,
  total_results: 80,
};